server:
  port: 8769
spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://register01:8760/eureka/,http://register02:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/*
      serviceId: service-ribbon
    api-b:
      path: /api-b/*
      serviceId: service-feign
    order:
      path: /order/**
      serviceId: order-api
    account:
      path: /account/**
      serviceId: account-service
      sensitiveHeaders:
  host:
    connect-timeout-millis: 60000
#    socket-timeout-millis: 3000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  maxAutoRetries: 1
  MaxAutoRetiesNextServer: 2

logging:
  level:
    org.springframework.cloud.netflix.zuul: DEBUG