server:
  port: 8761

eureka:
  instance:
    hostname: register01
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://register02:8760/eureka/

spring:
  application:
    name: registry

